#!/usr/bin/env bash

## Initialize a Docksal instance for testing the Utilities library
##
## Usage: fin init

# Abort if anything fails
set -e

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "$PROJECT_ROOT is not set"
	exit 1
fi

if [[ $DOCKER_RUNNING == "true" ]]; then
	echo -e "${green_bg} Step 1 ${NC}${green} Recreating services...${NC}"
	fin reset -f
else
	echo -e "${green_bg} Step 1 ${NC}${green} Creating services...${NC}"
	fin up
fi

echo -e "${green_bg} Step 2 ${NC}${green} Initializing Composer...${NC}"
fin composer install
echo
echo -e "${green} For PHPCS in the CLI, run:${NC} ${yellow}fin composer -n phpcs${NC}"
